[package]
description = "B-Rep topological data structures for remus"
edition.workspace = true
license.workspace = true
name = "remus-topology"
repository.workspace = true
rust-version.workspace = true
version = "0.1.0"

[dependencies]
remus-math.workspace = true
smallvec.workspace = true
thiserror.workspace = true


[dev-dependencies]
proptest.workspace = true

[features]
default = []

test-utils = []

[lints]
workspace = true
