[package]
description = "Shape healing (analysis, fixing, upgrading) for remus B-Rep models"
edition.workspace = true
license.workspace = true
name = "remus-heal"
repository.workspace = true
rust-version.workspace = true
version = "0.1.0"

[dependencies]
bitflags.workspace = true
log.workspace = true
remus-geometry.workspace = true
remus-math.workspace = true
remus-topology.workspace = true
thiserror.workspace = true

[dev-dependencies]
proptest.workspace = true
remus-topology = {workspace = true, features = ["test-utils"]}

[lints]
workspace = true
