[package]
description = "Topology algorithms: classification, validation, properties, distance"
edition.workspace = true
license.workspace = true
name = "remus-check"
repository.workspace = true
rust-version.workspace = true
version = "0.1.0"

[dependencies]
remus-geometry.workspace = true
remus-math.workspace = true
remus-topology.workspace = true
smallvec.workspace = true
thiserror.workspace = true

[dev-dependencies]
remus-topology = {workspace = true, features = ["test-utils"]}
proptest.workspace = true

[lints]
workspace = true
