[package]
description = "Walking-based fillet and chamfer engine for remus"
edition.workspace = true
license.workspace = true
name = "remus-blend"
repository.workspace = true
rust-version.workspace = true
version = "0.1.0"

[dependencies]
remus-math.workspace = true
remus-topology.workspace = true

log.workspace = true
thiserror.workspace = true

[dev-dependencies]
remus-topology = {workspace = true, features = ["test-utils"]}

[lints]
workspace = true
